In [1]:
!pip install -r requirements.txt

Requirement already satisfied: yahoo_fin in c:\program files\python310\lib\site-packages (from -r requirements.txt (line 1)) (0.8.9.1)
Collecting datetime
  Using cached DateTime-5.3-py3-none-any.whl (52 kB)
Requirement already satisfied: feedparser in c:\program files\python310\lib\site-packages (from -r requirements.txt (line 3)) (6.0.10)

ERROR: Could not find a version that satisfies the requirement ftplib (from versions: none)
ERROR: No matching distribution found for ftplib
WARNING: You are using pip version 22.0.4; however, version 23.3.1 is available.
You should consider upgrading via the 'C:\Program Files\Python310\python.exe -m pip install --upgrade pip' command.

In [14]:
import html5lib 
import requests_html
import yahoo_fin
import datetime
import feedparser
import ftplib
import io
import json
import pandas
import requests
import requests_html
import html5lib 
import pandas as pd
import numpy as np

In [3]:
from yahoo_fin import options

ticker= 'aapl'
def get_options_price(date, ticker= ticker):
    data= options.get_options_chain(ticker, date)
    dataDict = {'Call' : data["calls"], 'Put' : data["puts"]}
    return dataDict

In [4]:
dates = options.get_expiration_dates('aapl')

ListOptions = []
for date in dates :
    dataDict = get_options_price(date)
    for typ, data in dataDict.items():
        data["Type"] = typ
        data["Maturity"] = date
        ListOptions.append(data)

ListAllOptions = pd.concat(ListOptions)

In [5]:
ListAllOptions

,Contract Name,Last Trade Date,Strike,Last Price,Bid,Ask,Change,% Change,Volume,Open Interest,Implied Volatility,Type,Maturity
0,AAPL231208C00050000,2023-12-06 3:54PM EST,50.0,142.20,0.0,0.0,0.0,-,-,19,0.00%,Call,"December 8, 2023"
1,AAPL231208C00060000,2023-12-05 3:54PM EST,60.0,133.10,0.0,0.0,0.0,-,-,8,0.00%,Call,"December 8, 2023"
2,AAPL231208C00065000,2023-12-06 1:20PM EST,65.0,127.90,0.0,0.0,0.0,-,-,18,0.00%,Call,"December 8, 2023"
3,AAPL231208C00095000,2023-12-06 9:35AM EST,95.0,98.50,0.0,0.0,0.0,-,1,2,0.00%,Call,"December 8, 2023"
4,AAPL231208C00100000,2023-12-07 3:46PM EST,100.0,94.10,0.0,0.0,0.0,-,7,21,0.00%,Call,"December 8, 2023"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
44,AAPL260116P00275000,2023-12-05 12:24PM EST,275.0,81.50,0.0,0.0,0.0,-,11,0,0.00%,Put,"January 16, 2026"
45,AAPL260116P00285000,2023-11-28 3:33PM EST,285.0,95.13,0.0,0.0,0.0,-,-,0,0.00%,Put,"January 16, 2026"
46,AAPL260116P00290000,2023-12-07 11:19AM EST,290.0,95.80,0.0,0.0,0.0,-,1,0,0.00%,Put,"January 16, 2026"
47,AAPL260116P00300000,2023-12-07 1:40PM EST,300.0,105.47,0.0,0.0,0.0,-,202,204,0.00%,Put,"January 16, 2026"
48,AAPL260116P00310000,2023-12-01 10:39AM EST,310.0,119.75,0.0,0.0,0.0,-,8,0,0.00%,Put,"January 16, 2026"

In [10]:
ListAllOptions.describe()

,Strike,Last Price,Bid,Ask,Change,Open Interest
count,1707.000000,1707.000000,1707.000000,1707.000000,1707.0,1707.000000
mean,172.849443,29.977914,4.561271,4.671465,0.0,4297.932045
std,66.431808,39.255661,20.938915,21.424627,0.0,10602.860717
min,50.000000,0.010000,0.000000,0.000000,0.0,0.000000
25%,120.000000,0.290000,0.000000,0.000000,0.0,42.500000
50%,175.000000,9.300000,0.000000,0.000000,0.0,556.000000
75%,220.000000,49.900000,0.000000,0.000000,0.0,3194.000000
max,320.000000,148.590000,141.600000,143.050000,0.0,132851.000000

In [12]:
volume = ListAllOptions["Volume"]
volume.dtypes

dtype('O')

In [13]:
volume = volume[volume != '-']
print(len(volume))

1609

In [16]:
volume = volume.astype('float')
print(np.mean(volume))
np.median(volume)

563.8384089496582

9.0

In [ ]:
max()

In [ ]:
S_0 = 194.27

In [8]:
print(ListAllOptions['Volume'])

0      -
0    319
0     30
0      1
0      -
0      -
0      1
0      -
0      1
0      -
0      -
0      -
0      1
0      3
0      2
0     26
0      1
0      5
0      1
0     32
0      1
0    105
0    100
0      1
0      2
0     66
0      1
0     13
0      1
0      3
0      1
0    191
0      8
0      1
0      -
0      1
0      3
0    100
0      5
0      6
Name: Volume, dtype: object